# Generated by Django 4.2.4 on 2023-08-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
