# Generated by Django 4.2.4 on 2023-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_progress_mycourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(null=True, upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
