# Generated by Django 4.2.4 on 2023-08-29 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_alter_mycourses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.courses'),
        ),
        migrations.AlterUniqueTogether(
            name='mycourses',
            unique_together={('course', 'student_id')},
        ),
    ]
